GET http://localhost:8080/api/v1/planets?search=alderaan

###

POST http://localhost:8080/api/v1/planets
Content-Type: application/json

{
  "name": "Tatooine",
  "climate": "arid",
  "terrain": "desert"
}

###

GET http://localhost:8080/api/v1/planets/10

###

DELETE http://localhost:8080/api/v1/planets/1